### ISSUE TITLE
Incorrect header checksum error

### ISSUE THREAD

**Issue by Byrth** [JuliaIO/Tar.jl#111]
As indicated in [this ticket](https://github.com/JuliaTime/TimeZones.jl/issues/325), unpacking tzdata1997b.tar.gz seems to cause Tar.jl to throw an error:
```julia
Pkg.PlatformEngines.download_verify_unpack("https://data.iana.org/time-zones/releases/tzdata1997b.tar.gz", "8a6c0801bb2474342a48d6c2253e7983d50d4c6d80a1d455c06fa4e4434df3b3", "/root/.julia/artifacts/jl_rJlNRK"; verbose = true, quiet_download = false)
```

CentOS7, Julia 1.6.1

The `tar` utility in bash takes no issue with this file.

**Comment by Byrth** [comment]
Looks like it is. I only looked at the first post or two and didn't see the header checksum thing.

Within the TimeZones package, it erred on tzdata___.tar.gz: 1997b, 95d, 95g 95e, 1999f, 96e, 95i, 93g, and 1997c for me.

They are all old and IANA is likely hosting the original .tar.gzs, so I wonder if there is some kind of .tar standard issue here too.

**Comment by giordano** [comment]
Maybe try to reach out to [Paul Eggert](https://samueli.ucla.edu/people/paul-eggert/)?

**Comment by Byrth** [comment]
> Maybe try to reach out to [Paul Eggert](https://samueli.ucla.edu/people/paul-eggert/)?

I contacted Paul about this and he [replied](https://mm.icann.org/pipermail/tz/2021-May/030094.html). It looks like the bad checksums are due to a faulty SunOS `tar` utility and he suggests that we could perhaps allow them anyway.

I think that patching and rehosting them or disabling checksum verification (as it is redundant to an extent with SHA varification) are still probably the best options.

**Comment by StefanKarpinski** [comment]
I looked into this more and it turns out that the checksum *isn't* invalid. Rather, these old tarballs use a strange format when emitting numbers: they put leading spaces before the digits of the integer value. This is contrary to [the spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html), which states:

> All other fields are leading zero-filled octal numbers using digits from the ISO/IEC 646:1991 standard IRV. Each numeric field is terminated by one or more `<space>` or `NUL` characters.

However, this seems harmless to support parsing, so I'm preparing a PR to do that. The reason I had been misdiagnosing this as the checksum field being blank (all spaces) is a combination of things:

- we parse a checksum with leading spaces as the value zero
- in order to validate the checksum of the header, the field is filled with spaces
- we restore the original checksum data back if the check passes (so `Tar.list` sees the right value)
- but we were checking the value and throwing an error _before_ restoring the checksum data

Quite a conspiracy to make this seem like a different problem than it actually was.

**Comment by kmsquire** [comment]
Hi @StefanKarpinski, can you make a release so this fix is generally available without using master?

**Comment by kmsquire** [comment]
Actually, I just tried this version with https://data.iana.org/time-zones/releases/tzdata1997b.tar.gz, and it still fails with
```julia
(build) pkg> status
      Status `~/Workspace/ai/FifaTrialSmoothing/build/Project.toml`
  [9b87118b] PackageCompiler v1.4.0 `https://github.com/kmsquire/PackageCompiler.jl.git#kms/fix-include-lazy-artifacts`
  [a4e569a6] Tar `https://github.com/JuliaIO/Tar.jl.git#master`

julia> using Tar

julia> Tar.list("../tzdata1997b.tar")
ERROR: incorrect header checksum = 0; should be 2782
"africa\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0   444 \0 21140 \0     0 \0      53756  6305412777         \0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] read_standard_header(io::IOStream; buf::Vector{UInt8}, tee::Base.DevNull)
    @ Tar /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Tar/src/extract.jl:496
  [3] iterate_headers(callback::Tar.var"#71#72"{Vector{Tar.Header}}, tar::IOStream; raw::Bool, strict::Bool, buf::Vector{UInt8})
    @ Tar /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Tar/src/extract.jl:17
  [4] #68
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Tar/src/Tar.jl:131 [inlined]
  [5] open(f::Tar.var"#68#69"{Bool, Bool, Tar.var"#71#72"{Vector{Tar.Header}}}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
  [6] open
    @ ./io.jl:328 [inlined]
  [7] arg_read
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:60 [inlined]
  [8] #list#67
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Tar/src/Tar.jl:130 [inlined]
  [9] #list#70
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Tar/src/Tar.jl:141 [inlined]
 [10] list(tarball::String)
    @ Tar /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Tar/src/Tar.jl:140
 [11] top-level scope
    @ REPL[2]:1
```

**Comment by kmsquire** [comment]
Okay, I guess this might be because Tar is part of the standard library, and I was actually using that version above.

**Comment by StefanKarpinski** [comment]
Yeah, this is a major annoyance of stdlibs—you cannot freely load newer versions of them. Does it work for you on Julia master? And hopefully also on the Julia 1.7 betas?

**Comment by kmsquire** [comment]
It works fine on 1.6.2.  I haven't had the chance to test further.

**Comment by StefanKarpinski** [comment]
Ok, that seems good enough to verify that it's solved. Thanks for the feedback!
