### ISSUE TITLE
tree_hash giving invalid result

### ISSUE THREAD

**Issue by staticfloat** [JuliaIO/Tar.jl#59]
Calculating the tree hash of this tarball with `Tar.jl` gives different results as opposed to `git`:

# With `Julia`/`Tar.jl`
```julia
using Tar, Gzip_jll

url = "https://github.com/JuliaPackaging/Yggdrasil/releases/download/GCCBootstrap-v7.1.0+0/GCCBootstrap-aarch64-linux-gnu.v7.1.0.x86_64-linux-musl.unpacked.tar.gz"
filename = basename(url)
Base.download(url, filename)
gzip_proc = gzip(gz -> open(pipeline(`cat $filename`, `$gz -d`), read=true))
tree_hash = Tar.tree_hash(gzip_proc.out)

@show tree_hash
```
This yields `ae9d3fd6c826724c778c91fafc11d192dcd766a0`

# With `curl`/`tar`/`git`
```bash
# Do work in temporary directory
mkdir -p /tmp/tartest/download
mkdir -p /tmp/tartest/extract
url="https://github.com/JuliaPackaging/Yggdrasil/releases/download/GCCBootstrap-v7.1.0+0/GCCBootstrap-aarch64-linux-gnu.v7.1.0.x86_64-linux-musl.unpacked.tar.gz"
filename=/tmp/tartest/download/$(basename ${url})

curl -# -o ${filename} -L ${url}

cd /tmp/tartest/extract
tar zxf ${filename}
git init
git add .
git commit -m "foo"
git log -1 --pretty='%T'
```

This yields `d69cdbc9a382494e9e4d7ac7093266fc9be65aa8`

**Comment by staticfloat** [comment]
Ah, of course.  This is due to `skip_empty` defaulting to `false`.

**Comment by StefanKarpinski** [comment]
Right: by default if hashes the full content of the tarball, which will always match the git tree hash when the content can be represented by git, but differs when the tarball contains empty directories, which can be represented by a tarball but not by git.
