### ISSUE TITLE
Document and/or simplify how to create compressed tarball

### ISSUE THREAD

**Issue by mbauman** [JuliaIO/Tar.jl#66]
How do I create a `.tar.gz`?   Is this the way?

https://github.com/JuliaIO/Tar.jl/blob/095fb5afdc2f0f41220fc1d8fc50bad24a649026/test/perf/perf.jl#L62-L64

It'd be nice to document this or possibly even simplify it a bit.  I really just want to `Tar.create("dir", "dir.tar.gz")` and have it do what I want, but I get the dependency issues that incurs.

**Comment by StefanKarpinski** [comment]
That's one way to do it. The simplest if you have a gzip program is ``Tar.create("dir", pipeline(`gzip -9`, "dir.tar.gz"))``.
